site_name: Klassifikaatorite ja koodiloendite standard

theme:
  name: material
  language: et

nav:
  - Avaleht: index.md
  - Ülevaade: 01-ylevaade.md
  - Klassifikaatorite atribuudid: klassifikaator/atribuudid.md
  - Koodiloendite atribuudid: koodiloend/atribuudid.md