site_name: Klassifikaatorite ja koodiloendite standard

theme:
  name: material
  language: et

nav:
  - Avaleht: index.md
  - Ülevaade: 01-ylevaade.md
  - Klassifikaatorite kirjeldamine: klassifikaator/atribuudid.md
  - Koodiloendite kirjeldamine: koodiloend/atribuudid.md

extra_css:
  - stylesheets/style.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format